# Generated by Django 5.2.1 on 2025-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image1', models.URLField(blank=True)),
                ('image2', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
