# Generated by Django 5.2.1 on 2025-05-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saportfolio', '0002_project_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
