# Generated by Django 5.2.1 on 2025-05-29 16:11

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saportfolio', '0003_alter_project_image1_alter_project_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='saportfolio.project')),
            ],
        ),
    ]
