# Generated by Django 5.2.1 on 2025-05-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saportfolio', '0004_remove_project_image1_remove_project_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
