# Generated by Django 5.2.1 on 2025-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saportfolio', '0005_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
